<h1 style="color:blue">Praktikum 7. Masinõpe</h1>
<h3 style="color:blue">Klassifitseerimine</h3>
<h4>18. oktoober 2016 </h4>
<h4>Ülesannete esitamise tähtaeg 1. november.</h4>

Praktikumi eesmärgiks on saada praktiline kogemus erinevate klassifitseerimismeetoditega. Selleks kasutame Pythoni **scikit-learn** teeki (mis on vaja installida praktikumiülesannete lahendamiseks kasutatavasse conda keskkonda kas Jupyteri Conda tab'ilt või käsurealt käsuga 

`conda install scikit-learn`

### Andmete ettevalmistamine klassifitseerimisülesannete lahendamiseks

Andmed esitatakse kahe massiivina:
 * objektide vektorid
 * objektide sildid (*labels*)

Näidete jaoks kasutame scikit-learni mänguandmestikku Iris

In [4]:
from sklearn import datasets
iris = datasets.load_iris()
data, labels = iris.data, iris.target

In [5]:
data.shape

(150, 4)

In [10]:
labels.shape

(150,)

In [11]:
data

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [12]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], 
      dtype='<U10')

### Treening- ja testandmeteks jagamine

In [18]:
from sklearn import cross_validation as cv
data_train, data_test, labels_train, labels_test = cv.train_test_split(data, labels, test_size=0.2)

In [19]:
data_train.shape

(120, 4)

In [20]:
data_test.shape

(30, 4)

### Näide klassifitseerija treenimisest

In [21]:
from sklearn.naive_bayes import GaussianNB

In [49]:
# Treenime klassifitseerija
nb = GaussianNB()
nb.fit(data_train, labels_train)

GaussianNB(priors=None)

In [50]:
# Klassifitseerime testandmestikust esimese näite
nb.predict(data_test[0].reshape(1, -1))

array([1])

In [51]:
data_test[0].shape

(4,)

In [52]:
# Valideerime tulemuse
labels_test[0]

1

### Klassifitseerija hindamine

In [33]:
from sklearn import metrics

In [34]:
labels_predicted = nb.predict(data_test)

In [35]:
metrics.f1_score(labels_test, labels_predicted, average="weighted")

0.93333333333333335

### Klassifitseerija hindamine ristvalideerimise abil

In [36]:
scores = cv.cross_val_score(nb, data, labels, cv=5, scoring='f1_weighted')

In [37]:
scores

array([ 0.93333333,  0.96658312,  0.93265993,  0.93265993,  1.        ])

In [38]:
scores.mean()

0.95304726462621192

## Ül. 1 Dokumentide klassifitseerimine (3p)
**Andmed.** Kaustas *infolehed* on kaks kataloogi, millest esimene (PIL) sisaldab 250 Eestis registreeritud ravimi pakendi infolehte ning teine (SPC) sisaldab 250 ravimi spetsifikatsiooni. Kui infolehed on suunatud eelkõige ravimi tarvitajatele, siis spetsifikatsioonid pigem arstidele. Seega võiks arvata, et keelekasutus neis dokumentides on erinev.

**Eesmärk.** Dokumentide automaatne eristamine levinumaid klassifitseerimisalgoritme kasutades.

**1A. (1p)** Kirjutage kood, mille ülesandeks on:
* lugeda sisse dokumendid,
* teha dokumentidele EstNLTK abil morfoloogiline analüüs,
* eraldada dokumentidest tunnused,
* esitada dokumendid tunnusvektoritena (tunnuste suhtelised sagedused dokumendis),
* salvestada tunnusvektorid Numpy massiivina kettale,
* salvestada märgendid (*labels*) Numpy massiivina kettale.

**Tunnustena** kasutage:
* tekstisõnesid,
* lemmasid,
* sõnaliike (*partofspeech* EstNLTK väljundis),
* kogu grammatilist informatisoooni (*form* EstNLTK väljundis)

Iga tüüpi tunnuste kohta peaks tekkima eraldi massiiv.

**Ülesande lahenduses esitage nii kood, saadud 4 massiivi kui ka nende märgendid (ehk kokku 8 massiivi) (1p).**

**Vihjeid:**
* taaskasutage varasemates praktikumides loodud skripte!

**1B. (2p)** Realiseerige kood, mille ülesandeks on: 

* lugeda sisse eelmises ülesandes loodud tunnusvektorite massiivid,

* lugeda sisse vastavate massiivide märgendid,

* jagada andmed treening- ja testandmeteks (70-30),

* treenida treeningandmete peal järgmised klassifitseerijad:
    * *naive bayes*
    * *decision tree*
    * *k-nearest neighbours*
    
* testida treenitud klassifitseerijaid testandmestikul

** Lahenduses peaks näha kõikide treenitud klassifitseerijate F1-skoorid (kaalutud keskmist kasutades). Interpreteerige tulemusi (ehk püüdke oma sõnadega seletada, miks üks või teine lahendus paremini töötada võiks).**

**Vihjeid:**
* Klassifitseerijate import:
    * from sklearn.naive_bayes import GaussianNB
    * from sklearn.neighbors import KNeighborsClassifier
    * from sklearn.tree import DecisionTreeClassifier
    
Kõikidel klassifitseerijatel on samad meetodid (ehk neid kasutatakse täpselt nagu näites olevat Bayesi klassifitseerijat)

## Ül. 2 Keeletuvastus. (4p)
**Andmed.** Failis *et-en.par* on tükk eesti-inglise paralleelkorpusest (721 lauset). Võiks eeldada, et leidub selliseid n-gramme (siin kontekstis tähemitmikke), mis on omased ainult ühe või teise keele sõnadele.

**Eesmärk.** Eristada automaatselt eesti- ja ingliskeelset teksti. Eristada peaks olema võimalik 1
sõna korraga.

**2A. (2p)** Kirjutage kood, mille ülesandeks on:
* lugeda sisendfailist sisse andmed
* eraldada sisendsõnadest tunnused
* esitada sisendsõnad tunnusvektoritena
* salvestada tunnusvektorid Numpy massiivina kettale,
* salvestada märgendid (*labels*) Numpy massiivina kettale.

Tunnustena kasutage (binaarsena):
* 1-gramme
* 2-gramme
* 3-gramme

Iga andmestikus leiduva sõna jaoks peab tekkima 1 tunnusvektor (ehk mitu korda esinevaid
sõnu vaadeldakse ainult üks kord). Tunnused on binaarsed (0/1) ning indikeerivad, kas vastav
n-gramm on sõnas esindatud või mitte. Iga tüüpi tunnuste kohta peaks tekkima eraldi massiiv:

|          | Ngramm1          | Ngramm2  | ...     | NgrammN| 
| ------------- |:-------------:| -----:|
| sõna1      |  |   |    |    |
| sõna2      |        |    |    |    |
| ... |       |     |    |    |
| sõnaN |        |    |    |    |

**Lahendusena esitage lisaks koodile 3 massiivi koos vastavate märgenditega (seega kokku 6 massiivi).**

**2B. (2p)** Kirjutage kood, mille ülesandeks on:
* lugeda sisse eelmises ülesandes loodud tunnusvektorite massiivid,
* lugeda sisse vastavate massiivide märgendid,
* treenida treeningandmete peal järgmised klassifitseerijad:
     * *naive bayes*,
     * *decision tree*,
     * *k-nearest neighbours*,
* testida klassifitseerijaid 5x ristvalideerimist kasutades.


**Lahenduses peaks näha olema kõikide treenitud klassifitseerijate F1-skoorid (kaalutud keskmist kasutades). Interpreteerige tulemusi (ehk püüdke oma sõnadega seletada, miks üks või teine lahendus paremini töötada võiks).**